# fly.toml app configuration file generated for klinky on 2023-06-24T12:18:35+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "klinky"
primary_region = "sin"
#kill_signal = "SIGINT"
#kill_timeout = 5
#processes = []


#[http_service]
#  internal_port = 8080
#  force_https = true
#  auto_stop_machines = true
#  auto_start_machines = true
#  min_machines_running = 0
