name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checks out a copy of your repository
        uses: actions/checkout@v3

      - name: install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.40

      - name: run deploy by flyctl
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
